version: '3.8'

services:
  aishwarya-xerox:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - PORT=4173
    restart: unless-stopped
    volumes:
      - ./dist:/app/dist:ro